### ISSUE TITLE
lexicals not found in PIRC

### ISSUE THREAD

**Issue by plobsing** [parrot/pirc#9]
Originally reported in parrot TT #173 (http://trac.parrot.org/parrot/ticket/173)

lexicals can't be found in nested .subs.
the following works in parrot, but the generated bytecode doesn't seem to work:

{{{
.sub main
 .lex "x", $P0
 $P0 = new "Integer"
 $P0 = 42
 foo()
.end

.sub foo :outer("main")
 $P0 = find_lex "x"
 print $P0
.end
}}}

So, apparently, lexicals are not stored correctly.
This needs fixing.

**Comment by pmichaud** [comment]
The original source code is missing a "capture_lex" instruction -- see comment at http://trac.parrot.org/parrot/ticket/173#comment:8 .

Pm
